/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.scoping;

import de.protos.reqtext.scoping.AbstractReqTextScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ReqTextScopeProvider extends AbstractReqTextScopeProvider {
}
