/*
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.ui.tests;

import com.google.inject.Injector;
import de.protos.reqtext.ui.internal.ReqtextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ReqTextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ReqtextActivator.getInstance().getInjector("de.protos.reqtext.ReqText");
	}

}
