/*
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReqTextScopeProvider extends DelegatingScopeProvider {
}
