/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import de.protos.reqtext.ReqTextRuntimeModule;
import de.protos.reqtext.ReqTextStandaloneSetup;
import de.protos.reqtext.web.ReqTextWebModule;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ReqTextWebSetup extends ReqTextStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final ReqTextRuntimeModule runtimeModule = new ReqTextRuntimeModule();
    final ReqTextWebModule webModule = new ReqTextWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public ReqTextWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
