/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.validation;

import de.protos.reqtext.validation.AbstractReqTextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReqTextValidator extends AbstractReqTextValidator {
}
