/*
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.validation

import de.protos.reqtext.reqText.RMapEntry
import de.protos.reqtext.reqText.ReqTextPackage
import de.protos.reqtext.util.CCStringIndentation
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ReqTextValidator extends AbstractReqTextValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					ReqTextPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	@Check
	def checkMyMap(RMapEntry element) {
		val ccStringIndent = new CCStringIndentation(element.value);
		if (!ccStringIndent.validateIndentation())
			warning("Inconsistent indentation", element, ReqTextPackage.Literals.RMAP_ENTRY__VALUE);

	}

}
