/*
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.tests

import com.google.inject.Inject
import de.protos.reqtext.reqText.RModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ReqTextInjectorProvider)
class ReqTextParsingTest{

	@Inject
	ParseHelper<RModel> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
