/**
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.reqText;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.protos.reqtext.reqText.ReqTextPackage#getContent()
 * @model
 * @generated
 */
public interface Content extends EObject
{
} // Content
