/**
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.reqText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cross Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.protos.reqtext.reqText.CrossRef#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see de.protos.reqtext.reqText.ReqTextPackage#getCrossRef()
 * @model
 * @generated
 */
public interface CrossRef extends Content
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Content)
   * @see de.protos.reqtext.reqText.ReqTextPackage#getCrossRef_Ref()
   * @model
   * @generated
   */
  Content getRef();

  /**
   * Sets the value of the '{@link de.protos.reqtext.reqText.CrossRef#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Content value);

} // CrossRef
