/**
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.reqText;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.protos.reqtext.reqText.ReqTextFactory
 * @model kind="package"
 * @generated
 */
public interface ReqTextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "reqText";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.protos.de/reqtext/ReqText";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "reqText";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReqTextPackage eINSTANCE = de.protos.reqtext.reqText.impl.ReqTextPackageImpl.init();

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.RModelImpl <em>RModel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.RModelImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRModel()
   * @generated
   */
  int RMODEL = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL__CONTENTS = 1;

  /**
   * The number of structural features of the '<em>RModel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.ContentImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getContent()
   * @generated
   */
  int CONTENT = 1;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.RListImpl <em>RList</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.RListImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRList()
   * @generated
   */
  int RLIST = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RLIST__NAME = CONTENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RLIST__ENTRIES = CONTENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>RList</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RLIST_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.RMapImpl <em>RMap</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.RMapImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRMap()
   * @generated
   */
  int RMAP = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMAP__NAME = CONTENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMAP__ENTRIES = CONTENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>RMap</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMAP_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.RMapEntryImpl <em>RMap Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.RMapEntryImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRMapEntry()
   * @generated
   */
  int RMAP_ENTRY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMAP_ENTRY__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMAP_ENTRY__VALUE = 1;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMAP_ENTRY__REF = 2;

  /**
   * The number of structural features of the '<em>RMap Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMAP_ENTRY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.CrossRefImpl <em>Cross Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.CrossRefImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getCrossRef()
   * @generated
   */
  int CROSS_REF = 5;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_REF__REF = CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cross Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_REF_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.RImportImpl <em>RImport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.RImportImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRImport()
   * @generated
   */
  int RIMPORT = 6;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>RImport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIMPORT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.RModel <em>RModel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RModel</em>'.
   * @see de.protos.reqtext.reqText.RModel
   * @generated
   */
  EClass getRModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.RModel#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see de.protos.reqtext.reqText.RModel#getImports()
   * @see #getRModel()
   * @generated
   */
  EReference getRModel_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.RModel#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see de.protos.reqtext.reqText.RModel#getContents()
   * @see #getRModel()
   * @generated
   */
  EReference getRModel_Contents();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see de.protos.reqtext.reqText.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.RList <em>RList</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RList</em>'.
   * @see de.protos.reqtext.reqText.RList
   * @generated
   */
  EClass getRList();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.RList#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.protos.reqtext.reqText.RList#getName()
   * @see #getRList()
   * @generated
   */
  EAttribute getRList_Name();

  /**
   * Returns the meta object for the attribute list '{@link de.protos.reqtext.reqText.RList#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Entries</em>'.
   * @see de.protos.reqtext.reqText.RList#getEntries()
   * @see #getRList()
   * @generated
   */
  EAttribute getRList_Entries();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.RMap <em>RMap</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RMap</em>'.
   * @see de.protos.reqtext.reqText.RMap
   * @generated
   */
  EClass getRMap();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.RMap#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.protos.reqtext.reqText.RMap#getName()
   * @see #getRMap()
   * @generated
   */
  EAttribute getRMap_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.RMap#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see de.protos.reqtext.reqText.RMap#getEntries()
   * @see #getRMap()
   * @generated
   */
  EReference getRMap_Entries();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.RMapEntry <em>RMap Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RMap Entry</em>'.
   * @see de.protos.reqtext.reqText.RMapEntry
   * @generated
   */
  EClass getRMapEntry();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.RMapEntry#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.protos.reqtext.reqText.RMapEntry#getName()
   * @see #getRMapEntry()
   * @generated
   */
  EAttribute getRMapEntry_Name();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.RMapEntry#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.protos.reqtext.reqText.RMapEntry#getValue()
   * @see #getRMapEntry()
   * @generated
   */
  EAttribute getRMapEntry_Value();

  /**
   * Returns the meta object for the reference '{@link de.protos.reqtext.reqText.RMapEntry#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see de.protos.reqtext.reqText.RMapEntry#getRef()
   * @see #getRMapEntry()
   * @generated
   */
  EReference getRMapEntry_Ref();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.CrossRef <em>Cross Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cross Ref</em>'.
   * @see de.protos.reqtext.reqText.CrossRef
   * @generated
   */
  EClass getCrossRef();

  /**
   * Returns the meta object for the reference '{@link de.protos.reqtext.reqText.CrossRef#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see de.protos.reqtext.reqText.CrossRef#getRef()
   * @see #getCrossRef()
   * @generated
   */
  EReference getCrossRef_Ref();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.RImport <em>RImport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RImport</em>'.
   * @see de.protos.reqtext.reqText.RImport
   * @generated
   */
  EClass getRImport();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.RImport#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see de.protos.reqtext.reqText.RImport#getImportURI()
   * @see #getRImport()
   * @generated
   */
  EAttribute getRImport_ImportURI();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ReqTextFactory getReqTextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.RModelImpl <em>RModel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.RModelImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRModel()
     * @generated
     */
    EClass RMODEL = eINSTANCE.getRModel();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMODEL__IMPORTS = eINSTANCE.getRModel_Imports();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMODEL__CONTENTS = eINSTANCE.getRModel_Contents();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.ContentImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.RListImpl <em>RList</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.RListImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRList()
     * @generated
     */
    EClass RLIST = eINSTANCE.getRList();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RLIST__NAME = eINSTANCE.getRList_Name();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RLIST__ENTRIES = eINSTANCE.getRList_Entries();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.RMapImpl <em>RMap</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.RMapImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRMap()
     * @generated
     */
    EClass RMAP = eINSTANCE.getRMap();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RMAP__NAME = eINSTANCE.getRMap_Name();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMAP__ENTRIES = eINSTANCE.getRMap_Entries();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.RMapEntryImpl <em>RMap Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.RMapEntryImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRMapEntry()
     * @generated
     */
    EClass RMAP_ENTRY = eINSTANCE.getRMapEntry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RMAP_ENTRY__NAME = eINSTANCE.getRMapEntry_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RMAP_ENTRY__VALUE = eINSTANCE.getRMapEntry_Value();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMAP_ENTRY__REF = eINSTANCE.getRMapEntry_Ref();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.CrossRefImpl <em>Cross Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.CrossRefImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getCrossRef()
     * @generated
     */
    EClass CROSS_REF = eINSTANCE.getCrossRef();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CROSS_REF__REF = eINSTANCE.getCrossRef_Ref();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.RImportImpl <em>RImport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.RImportImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRImport()
     * @generated
     */
    EClass RIMPORT = eINSTANCE.getRImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIMPORT__IMPORT_URI = eINSTANCE.getRImport_ImportURI();

  }

} //ReqTextPackage
