/**
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.reqText;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.protos.reqtext.reqText.ReqTextPackage
 * @generated
 */
public interface ReqTextFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReqTextFactory eINSTANCE = de.protos.reqtext.reqText.impl.ReqTextFactoryImpl.init();

  /**
   * Returns a new object of class '<em>RModel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RModel</em>'.
   * @generated
   */
  RModel createRModel();

  /**
   * Returns a new object of class '<em>Content</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content</em>'.
   * @generated
   */
  Content createContent();

  /**
   * Returns a new object of class '<em>RList</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RList</em>'.
   * @generated
   */
  RList createRList();

  /**
   * Returns a new object of class '<em>RMap</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RMap</em>'.
   * @generated
   */
  RMap createRMap();

  /**
   * Returns a new object of class '<em>RMap Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RMap Entry</em>'.
   * @generated
   */
  RMapEntry createRMapEntry();

  /**
   * Returns a new object of class '<em>Cross Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cross Ref</em>'.
   * @generated
   */
  CrossRef createCrossRef();

  /**
   * Returns a new object of class '<em>RImport</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RImport</em>'.
   * @generated
   */
  RImport createRImport();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ReqTextPackage getReqTextPackage();

} //ReqTextFactory
