/**
 * generated by Xtext 2.10.0
 */
package de.protos.reqtext.reqText;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.protos.reqtext.reqText.ReqTextFactory
 * @model kind="package"
 * @generated
 */
public interface ReqTextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "reqText";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.protos.de/reqtext/ReqText";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "reqText";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReqTextPackage eINSTANCE = de.protos.reqtext.reqText.impl.ReqTextPackageImpl.init();

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.RModelImpl <em>RModel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.RModelImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRModel()
   * @generated
   */
  int RMODEL = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL__STATES = 1;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL__CLASSES = 2;

  /**
   * The feature id for the '<em><b>Objs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL__OBJS = 3;

  /**
   * The number of structural features of the '<em>RModel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.SpecObjectImpl <em>Spec Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.SpecObjectImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getSpecObject()
   * @generated
   */
  int SPEC_OBJECT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__STATE = 2;

  /**
   * The feature id for the '<em><b>Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__CLASS = 3;

  /**
   * The feature id for the '<em><b>Version</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__VERSION = 4;

  /**
   * The feature id for the '<em><b>Image</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__IMAGE = 5;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__REFERENCE = 6;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT__CHILDREN = 7;

  /**
   * The number of structural features of the '<em>Spec Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_OBJECT_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.StateImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getState()
   * @generated
   */
  int STATE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.ClassImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getClass_()
   * @generated
   */
  int CLASS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__NAME = 0;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.VersionImpl <em>Version</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.VersionImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getVersion()
   * @generated
   */
  int VERSION = 4;

  /**
   * The feature id for the '<em><b>Major</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__MAJOR = 0;

  /**
   * The feature id for the '<em><b>Minor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__MINOR = 1;

  /**
   * The number of structural features of the '<em>Version</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.protos.reqtext.reqText.impl.RImportImpl <em>RImport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.protos.reqtext.reqText.impl.RImportImpl
   * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRImport()
   * @generated
   */
  int RIMPORT = 5;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>RImport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIMPORT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.RModel <em>RModel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RModel</em>'.
   * @see de.protos.reqtext.reqText.RModel
   * @generated
   */
  EClass getRModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.RModel#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see de.protos.reqtext.reqText.RModel#getImports()
   * @see #getRModel()
   * @generated
   */
  EReference getRModel_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.RModel#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see de.protos.reqtext.reqText.RModel#getStates()
   * @see #getRModel()
   * @generated
   */
  EReference getRModel_States();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.RModel#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see de.protos.reqtext.reqText.RModel#getClasses()
   * @see #getRModel()
   * @generated
   */
  EReference getRModel_Classes();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.RModel#getObjs <em>Objs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objs</em>'.
   * @see de.protos.reqtext.reqText.RModel#getObjs()
   * @see #getRModel()
   * @generated
   */
  EReference getRModel_Objs();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.SpecObject <em>Spec Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Spec Object</em>'.
   * @see de.protos.reqtext.reqText.SpecObject
   * @generated
   */
  EClass getSpecObject();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.SpecObject#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getName()
   * @see #getSpecObject()
   * @generated
   */
  EAttribute getSpecObject_Name();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.SpecObject#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getDescription()
   * @see #getSpecObject()
   * @generated
   */
  EAttribute getSpecObject_Description();

  /**
   * Returns the meta object for the reference '{@link de.protos.reqtext.reqText.SpecObject#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getState()
   * @see #getSpecObject()
   * @generated
   */
  EReference getSpecObject_State();

  /**
   * Returns the meta object for the reference '{@link de.protos.reqtext.reqText.SpecObject#getClass_ <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Class</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getClass_()
   * @see #getSpecObject()
   * @generated
   */
  EReference getSpecObject_Class();

  /**
   * Returns the meta object for the containment reference '{@link de.protos.reqtext.reqText.SpecObject#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Version</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getVersion()
   * @see #getSpecObject()
   * @generated
   */
  EReference getSpecObject_Version();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.SpecObject#getImage <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Image</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getImage()
   * @see #getSpecObject()
   * @generated
   */
  EAttribute getSpecObject_Image();

  /**
   * Returns the meta object for the reference '{@link de.protos.reqtext.reqText.SpecObject#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getReference()
   * @see #getSpecObject()
   * @generated
   */
  EReference getSpecObject_Reference();

  /**
   * Returns the meta object for the containment reference list '{@link de.protos.reqtext.reqText.SpecObject#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see de.protos.reqtext.reqText.SpecObject#getChildren()
   * @see #getSpecObject()
   * @generated
   */
  EReference getSpecObject_Children();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see de.protos.reqtext.reqText.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.protos.reqtext.reqText.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see de.protos.reqtext.reqText.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.Class#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.protos.reqtext.reqText.Class#getName()
   * @see #getClass_()
   * @generated
   */
  EAttribute getClass_Name();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.Version <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Version</em>'.
   * @see de.protos.reqtext.reqText.Version
   * @generated
   */
  EClass getVersion();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.Version#getMajor <em>Major</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Major</em>'.
   * @see de.protos.reqtext.reqText.Version#getMajor()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Major();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.Version#getMinor <em>Minor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minor</em>'.
   * @see de.protos.reqtext.reqText.Version#getMinor()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Minor();

  /**
   * Returns the meta object for class '{@link de.protos.reqtext.reqText.RImport <em>RImport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RImport</em>'.
   * @see de.protos.reqtext.reqText.RImport
   * @generated
   */
  EClass getRImport();

  /**
   * Returns the meta object for the attribute '{@link de.protos.reqtext.reqText.RImport#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see de.protos.reqtext.reqText.RImport#getImportURI()
   * @see #getRImport()
   * @generated
   */
  EAttribute getRImport_ImportURI();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ReqTextFactory getReqTextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.RModelImpl <em>RModel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.RModelImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRModel()
     * @generated
     */
    EClass RMODEL = eINSTANCE.getRModel();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMODEL__IMPORTS = eINSTANCE.getRModel_Imports();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMODEL__STATES = eINSTANCE.getRModel_States();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMODEL__CLASSES = eINSTANCE.getRModel_Classes();

    /**
     * The meta object literal for the '<em><b>Objs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMODEL__OBJS = eINSTANCE.getRModel_Objs();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.SpecObjectImpl <em>Spec Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.SpecObjectImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getSpecObject()
     * @generated
     */
    EClass SPEC_OBJECT = eINSTANCE.getSpecObject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPEC_OBJECT__NAME = eINSTANCE.getSpecObject_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPEC_OBJECT__DESCRIPTION = eINSTANCE.getSpecObject_Description();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC_OBJECT__STATE = eINSTANCE.getSpecObject_State();

    /**
     * The meta object literal for the '<em><b>Class</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC_OBJECT__CLASS = eINSTANCE.getSpecObject_Class();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC_OBJECT__VERSION = eINSTANCE.getSpecObject_Version();

    /**
     * The meta object literal for the '<em><b>Image</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPEC_OBJECT__IMAGE = eINSTANCE.getSpecObject_Image();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC_OBJECT__REFERENCE = eINSTANCE.getSpecObject_Reference();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC_OBJECT__CHILDREN = eINSTANCE.getSpecObject_Children();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.StateImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.ClassImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS__NAME = eINSTANCE.getClass_Name();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.VersionImpl <em>Version</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.VersionImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getVersion()
     * @generated
     */
    EClass VERSION = eINSTANCE.getVersion();

    /**
     * The meta object literal for the '<em><b>Major</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__MAJOR = eINSTANCE.getVersion_Major();

    /**
     * The meta object literal for the '<em><b>Minor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__MINOR = eINSTANCE.getVersion_Minor();

    /**
     * The meta object literal for the '{@link de.protos.reqtext.reqText.impl.RImportImpl <em>RImport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.protos.reqtext.reqText.impl.RImportImpl
     * @see de.protos.reqtext.reqText.impl.ReqTextPackageImpl#getRImport()
     * @generated
     */
    EClass RIMPORT = eINSTANCE.getRImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIMPORT__IMPORT_URI = eINSTANCE.getRImport_ImportURI();

  }

} //ReqTextPackage
