/**
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.reqText;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RModel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.protos.reqtext.reqText.RModel#getImports <em>Imports</em>}</li>
 *   <li>{@link de.protos.reqtext.reqText.RModel#getContents <em>Contents</em>}</li>
 * </ul>
 *
 * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel()
 * @model
 * @generated
 */
public interface RModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.reqtext.reqText.RImport}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel_Imports()
   * @model containment="true"
   * @generated
   */
  EList<RImport> getImports();

  /**
   * Returns the value of the '<em><b>Contents</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.reqtext.reqText.Content}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contents</em>' containment reference list.
   * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel_Contents()
   * @model containment="true"
   * @generated
   */
  EList<Content> getContents();

} // RModel
