/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.reqText;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RModel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.protos.reqtext.reqText.RModel#getImports <em>Imports</em>}</li>
 *   <li>{@link de.protos.reqtext.reqText.RModel#getStates <em>States</em>}</li>
 *   <li>{@link de.protos.reqtext.reqText.RModel#getClasses <em>Classes</em>}</li>
 *   <li>{@link de.protos.reqtext.reqText.RModel#getObjs <em>Objs</em>}</li>
 * </ul>
 *
 * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel()
 * @model
 * @generated
 */
public interface RModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.reqtext.reqText.RImport}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel_Imports()
   * @model containment="true"
   * @generated
   */
  EList<RImport> getImports();

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.reqtext.reqText.State}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>States</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.reqtext.reqText.Class}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel_Classes()
   * @model containment="true"
   * @generated
   */
  EList<de.protos.reqtext.reqText.Class> getClasses();

  /**
   * Returns the value of the '<em><b>Objs</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.reqtext.reqText.SpecObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objs</em>' containment reference list.
   * @see de.protos.reqtext.reqText.ReqTextPackage#getRModel_Objs()
   * @model containment="true"
   * @generated
   */
  EList<SpecObject> getObjs();

} // RModel
