/*
 * generated by Xtext 2.10.0
 */
package de.protos.reqtext.parser.antlr;

import com.google.inject.Inject;
import de.protos.reqtext.parser.antlr.internal.InternalReqTextParser;
import de.protos.reqtext.services.ReqTextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ReqTextParser extends AbstractAntlrParser {

	@Inject
	private ReqTextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReqTextParser createParser(XtextTokenStream stream) {
		return new InternalReqTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RModel";
	}

	public ReqTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReqTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
