/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.reqText.impl;

import de.protos.reqtext.reqText.Image;
import de.protos.reqtext.reqText.RImport;
import de.protos.reqtext.reqText.RModel;
import de.protos.reqtext.reqText.ReqTextFactory;
import de.protos.reqtext.reqText.ReqTextPackage;
import de.protos.reqtext.reqText.SpecObject;
import de.protos.reqtext.reqText.State;
import de.protos.reqtext.reqText.Version;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ReqTextFactoryImpl extends EFactoryImpl implements ReqTextFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ReqTextFactory init()
  {
    try
    {
      ReqTextFactory theReqTextFactory = (ReqTextFactory)EPackage.Registry.INSTANCE.getEFactory(ReqTextPackage.eNS_URI);
      if (theReqTextFactory != null)
      {
        return theReqTextFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ReqTextFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReqTextFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ReqTextPackage.RMODEL: return createRModel();
      case ReqTextPackage.SPEC_OBJECT: return createSpecObject();
      case ReqTextPackage.IMAGE: return createImage();
      case ReqTextPackage.STATE: return createState();
      case ReqTextPackage.CLASS: return createClass();
      case ReqTextPackage.VERSION: return createVersion();
      case ReqTextPackage.RIMPORT: return createRImport();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RModel createRModel()
  {
    RModelImpl rModel = new RModelImpl();
    return rModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SpecObject createSpecObject()
  {
    SpecObjectImpl specObject = new SpecObjectImpl();
    return specObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Image createImage()
  {
    ImageImpl image = new ImageImpl();
    return image;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public State createState()
  {
    StateImpl state = new StateImpl();
    return state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public de.protos.reqtext.reqText.Class createClass()
  {
    ClassImpl class_ = new ClassImpl();
    return class_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Version createVersion()
  {
    VersionImpl version = new VersionImpl();
    return version;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RImport createRImport()
  {
    RImportImpl rImport = new RImportImpl();
    return rImport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReqTextPackage getReqTextPackage()
  {
    return (ReqTextPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ReqTextPackage getPackage()
  {
    return ReqTextPackage.eINSTANCE;
  }

} //ReqTextFactoryImpl
