/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.reqText.impl;

import de.protos.reqtext.reqText.RImport;
import de.protos.reqtext.reqText.RModel;
import de.protos.reqtext.reqText.ReqTextPackage;
import de.protos.reqtext.reqText.SpecObject;
import de.protos.reqtext.reqText.State;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>RModel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.protos.reqtext.reqText.impl.RModelImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link de.protos.reqtext.reqText.impl.RModelImpl#getStates <em>States</em>}</li>
 *   <li>{@link de.protos.reqtext.reqText.impl.RModelImpl#getClasses <em>Classes</em>}</li>
 *   <li>{@link de.protos.reqtext.reqText.impl.RModelImpl#getObjs <em>Objs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RModelImpl extends MinimalEObjectImpl.Container implements RModel
{
  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<RImport> imports;

  /**
   * The cached value of the '{@link #getStates() <em>States</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStates()
   * @generated
   * @ordered
   */
  protected EList<State> states;

  /**
   * The cached value of the '{@link #getClasses() <em>Classes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClasses()
   * @generated
   * @ordered
   */
  protected EList<de.protos.reqtext.reqText.Class> classes;

  /**
   * The cached value of the '{@link #getObjs() <em>Objs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjs()
   * @generated
   * @ordered
   */
  protected EList<SpecObject> objs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReqTextPackage.Literals.RMODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<RImport> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<RImport>(RImport.class, this, ReqTextPackage.RMODEL__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<State> getStates()
  {
    if (states == null)
    {
      states = new EObjectContainmentEList<State>(State.class, this, ReqTextPackage.RMODEL__STATES);
    }
    return states;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<de.protos.reqtext.reqText.Class> getClasses()
  {
    if (classes == null)
    {
      classes = new EObjectContainmentEList<de.protos.reqtext.reqText.Class>(de.protos.reqtext.reqText.Class.class, this, ReqTextPackage.RMODEL__CLASSES);
    }
    return classes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<SpecObject> getObjs()
  {
    if (objs == null)
    {
      objs = new EObjectContainmentEList<SpecObject>(SpecObject.class, this, ReqTextPackage.RMODEL__OBJS);
    }
    return objs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ReqTextPackage.RMODEL__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case ReqTextPackage.RMODEL__STATES:
        return ((InternalEList<?>)getStates()).basicRemove(otherEnd, msgs);
      case ReqTextPackage.RMODEL__CLASSES:
        return ((InternalEList<?>)getClasses()).basicRemove(otherEnd, msgs);
      case ReqTextPackage.RMODEL__OBJS:
        return ((InternalEList<?>)getObjs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ReqTextPackage.RMODEL__IMPORTS:
        return getImports();
      case ReqTextPackage.RMODEL__STATES:
        return getStates();
      case ReqTextPackage.RMODEL__CLASSES:
        return getClasses();
      case ReqTextPackage.RMODEL__OBJS:
        return getObjs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ReqTextPackage.RMODEL__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends RImport>)newValue);
        return;
      case ReqTextPackage.RMODEL__STATES:
        getStates().clear();
        getStates().addAll((Collection<? extends State>)newValue);
        return;
      case ReqTextPackage.RMODEL__CLASSES:
        getClasses().clear();
        getClasses().addAll((Collection<? extends de.protos.reqtext.reqText.Class>)newValue);
        return;
      case ReqTextPackage.RMODEL__OBJS:
        getObjs().clear();
        getObjs().addAll((Collection<? extends SpecObject>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ReqTextPackage.RMODEL__IMPORTS:
        getImports().clear();
        return;
      case ReqTextPackage.RMODEL__STATES:
        getStates().clear();
        return;
      case ReqTextPackage.RMODEL__CLASSES:
        getClasses().clear();
        return;
      case ReqTextPackage.RMODEL__OBJS:
        getObjs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ReqTextPackage.RMODEL__IMPORTS:
        return imports != null && !imports.isEmpty();
      case ReqTextPackage.RMODEL__STATES:
        return states != null && !states.isEmpty();
      case ReqTextPackage.RMODEL__CLASSES:
        return classes != null && !classes.isEmpty();
      case ReqTextPackage.RMODEL__OBJS:
        return objs != null && !objs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //RModelImpl
