/**
 * generated by Xtext 2.9.2
 */
package de.protos.reqtext.reqText.util;

import de.protos.reqtext.reqText.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see de.protos.reqtext.reqText.ReqTextPackage
 * @generated
 */
public class ReqTextAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static ReqTextPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReqTextAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = ReqTextPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReqTextSwitch<Adapter> modelSwitch =
    new ReqTextSwitch<Adapter>()
    {
      @Override
      public Adapter caseRModel(RModel object)
      {
        return createRModelAdapter();
      }
      @Override
      public Adapter caseContent(Content object)
      {
        return createContentAdapter();
      }
      @Override
      public Adapter caseRList(RList object)
      {
        return createRListAdapter();
      }
      @Override
      public Adapter caseRMap(RMap object)
      {
        return createRMapAdapter();
      }
      @Override
      public Adapter caseRMapEntry(RMapEntry object)
      {
        return createRMapEntryAdapter();
      }
      @Override
      public Adapter caseCrossRef(CrossRef object)
      {
        return createCrossRefAdapter();
      }
      @Override
      public Adapter caseRImport(RImport object)
      {
        return createRImportAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link de.protos.reqtext.reqText.RModel <em>RModel</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.protos.reqtext.reqText.RModel
   * @generated
   */
  public Adapter createRModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.protos.reqtext.reqText.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.protos.reqtext.reqText.Content
   * @generated
   */
  public Adapter createContentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.protos.reqtext.reqText.RList <em>RList</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.protos.reqtext.reqText.RList
   * @generated
   */
  public Adapter createRListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.protos.reqtext.reqText.RMap <em>RMap</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.protos.reqtext.reqText.RMap
   * @generated
   */
  public Adapter createRMapAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.protos.reqtext.reqText.RMapEntry <em>RMap Entry</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.protos.reqtext.reqText.RMapEntry
   * @generated
   */
  public Adapter createRMapEntryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.protos.reqtext.reqText.CrossRef <em>Cross Ref</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.protos.reqtext.reqText.CrossRef
   * @generated
   */
  public Adapter createCrossRefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.protos.reqtext.reqText.RImport <em>RImport</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.protos.reqtext.reqText.RImport
   * @generated
   */
  public Adapter createRImportAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //ReqTextAdapterFactory
