/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext;

import de.protos.reqtext.AbstractReqTextRuntimeModule;
import de.protos.reqtext.converter.FeaturizerConverterService;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqTextRuntimeModule extends AbstractReqTextRuntimeModule {
  @Override
  public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
    return ImportUriGlobalScopeProvider.class;
  }
  
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return FeaturizerConverterService.class;
  }
}
