/*
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReqTextStandaloneSetup extends ReqTextStandaloneSetupGenerated {

	def static void doSetup() {
		new ReqTextStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
