/**
 * generated by Xtext 2.9.1
 */
package de.protos.reqtext.ui;

import de.protos.reqtext.ui.AbstractReqTextUiModule;
import de.protos.reqtext.ui.autoedit.FeaturizerAutoEditStrategyProvider;
import de.protos.reqtext.ui.autoedit.TokenTypeToPartitionMapper;
import de.protos.reqtext.ui.highlight.FeaturizerHighlightingConfig;
import de.protos.reqtext.ui.highlight.FeaturizerSemanticHighlighter;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.eclipse.xtext.ui.editor.model.TerminalsTokenTypeToPartitionMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ReqTextUiModule extends AbstractReqTextUiModule {
  public Class<? extends IHighlightingConfiguration> bindSemanticConfig() {
    return FeaturizerHighlightingConfig.class;
  }
  
  public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
    return FeaturizerSemanticHighlighter.class;
  }
  
  @Override
  public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
    return FeaturizerAutoEditStrategyProvider.class;
  }
  
  public Class<? extends TerminalsTokenTypeToPartitionMapper> bindTerminalsTokenTypeToPartitionMapper() {
    return TokenTypeToPartitionMapper.class;
  }
  
  public ReqTextUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
